bind v split-window -h
bind - split-window -v
bind s choose-tree -Zs

set -g base-index 1

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -sg escape-time 10

set -g renumber-windows on

# True color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Set Status bar color
set -g status-style "bg=colour153,fg=black"
# Highlight the active window
set -g window-status-current-style "bg=#24283b,fg=colour153,bold"
# Padding for highlight
set -g window-status-current-format " #I:#W#F "
set -g window-status-format " #I:#W#F "


# Move window to the left
bind Left swap-window -t -1\; select-window -t -1

# Move window to the right
bind Right swap-window -t +1\; select-window -t +1

#reload
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded from tmux folder!"

# Prefix + o to fuzzy find windows in a popup
bind o display-popup -E "tmux list-windows -a -F '#{session_name}:#{window_index} - #{window_name}' | grep -v \"^$(tmux display-message -p '#S:#I')\" | fzf --reverse | cut -d \" \" -f 1 | xargs tmux select-window -t"

# Prefix + p for fuzzy find sessions in a popup
bind p display-popup -E "tmux list-sessions -F '#{session_name}' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
